import os

SEED = 42
ROBUSTNESS_SEEDS = [42, 123, 256, 512, 777]

CROP_SIZE = (100, 110)
NUM_CLASSES = 4
BACKGROUND_INDEX = 0
RV_INDEX = 1
MYO_INDEX = 2
LV_INDEX = 3
FOREGROUND_INDICES = [RV_INDEX, MYO_INDEX, LV_INDEX]
STRUCTURE_NAMES = {RV_INDEX: "RV", MYO_INDEX: "Myo", LV_INDEX: "LV"}

PATHOLOGIES = ["NOR", "MINF", "DCM", "HCM", "ARV"]

N_TRAIN_PATIENTS = 100
N_TEST_PATIENTS = 50
N_PER_CLASS_TRAIN = 20
N_PER_CLASS_TEST = 10
N_FOLDS = 5

EPOCHS = 100
BATCH_SIZE = 8
LEARNING_RATE = 8e-5
LR_REDUCE_FACTOR = 0.9
LR_REDUCE_PATIENCE = 10
LR_FLOOR = 1e-6

LOSS_DICE_WEIGHT = 1.0
LOSS_FOCAL_WEIGHT = 1.0
LOSS_CE_WEIGHT = 0.5
FOCAL_GAMMA = 2.0

DROPOUT_RATE = 0.3
MC_PASSES = 10
DROPOUT_PLACEMENT = "encoder"

AUG_FLIP_PROB = 0.5
AUG_ROTATION_DEG = 15.0
AUG_SCALE_RANGE = (0.85, 1.15)
AUG_BRIGHTNESS = 0.20
AUG_CONTRAST = 0.20

ECE_BINS = 15
RELIABILITY_BINS = 15
BIN_SWEEP = [10, 15, 20]

BACKBONES = ["efficientnet-b3", "efficientnet-b4", "swinunet", "mobilevit-s"]
PRIMARY_BACKBONE = "efficientnet-b4"

QC_THRESHOLDS = [0.10, 0.20, 0.30]
FAILURE_DSC = 0.85

BOOTSTRAP_RESAMPLES = 1000

DATA_ROOT = os.environ.get("ACDC_ROOT", "./ACDC/database")
OUTPUT_ROOT = os.environ.get("OUTPUT_ROOT", "./outputs")
